services:
  test_db:
    container_name: geo_test_db
    image: postgis/postgis:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
  
  data_service:
    container_name: geo_data_service
    build:
      context: .
      dockerfile: geo_data_service/Dockerfile
    volumes:
      - ./src/:/geo_data_service/app/data
    environment:
      - DATABASE_URL=postgresql+asyncpg://hello_fastapi:hello_fastapi@geo_test_db:5432/hello_fastapi_dev
    depends_on:
      - test_db 
  geo_service:
    container_name: geo_service
    build:
      context: .
      dockerfile: geo_service/Dockerfile
    volumes:
      - ./src/:/geo_service/app/
    ports:
      - "8000:8000"
    depends_on:
      - test_db


volumes:
  postgres_data:
